TheKitchen/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TheKitchen.Models
{
    /// <summary>
    /// The model class for a recipe
    /// </summary>
    public class Recipe
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "User is required")]
        public int UserId { get; set; }

        [Required(ErrorMessage = "Title is required")]
        [StringLength(45, MinimumLength = 2)]
        [Display(Name = "Title", Prompt = "Title")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Description is required")]
        [StringLength(500)]
        [Display(Name = "Description", Prompt = "Description")]
        public string Description { get; set; }

        [Required(ErrorMessage = "You must include at least one ingredient.")]
        public List<RecipeIngredient> Ingredients {get; set;}

        [Required(ErrorMessage = "You must include at least one instruction step.")]
        public List<Instruction> Directions { get; set; }

        public byte[] Picture { get; set; }

        public DateTime DateAdded { get; set; }
        
        public int TasteRating { get; set; }
        
        public int DifficultyRating { get; set; }

    }
}

TheKitchen/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySqlConnector;
using TheKitchen.DAL;
using TheKitchen.Models;

namespace TheKitchen.Controllers
{
    /// <summary>
    /// The RecipeController class
    /// </summary>
    public class RecipeController: Controller
    {
        private readonly RecipeDAL recipeData;
        private readonly UserDAL userData;

        /// <summary>
        /// RecipeController constructor
        /// </summary>
        public RecipeController()
        {
            this.recipeData = new RecipeDAL();
            this.userData = new UserDAL();
        }

        /// <summary>
        /// Returns user to recipe index page
        /// </summary>
        /// <returns></returns>
        [HttpGet("Recipe/Index")]
        public ActionResult Index()
        {
            try
            {
                return View("Index",recipeData.GetAllRecipes());
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return StatusCode(500, "Something went wrong. Please try again");
            }
        }

        /// <summary>
        /// Returns user to a specific recipe page
        /// </summary>
        /// <param name="id">recipe ID to view</param>
        [HttpGet("Recipe/Details/{id}")]
        public ActionResult Details(int id)
        {
            try
            {
                Recipe recipe = recipeData.GetRecipe(id);
                if (recipe != null)
                {
                    if (User != null && User.Identity.IsAuthenticated)
                    {
                        var userEmail = User.FindFirst(ClaimTypes.Email).Value;
                        var user = userData.GetUser(userEmail);

                        RecipeBookDAL recipeBookDAL = new RecipeBookDAL();
                        List<RecipeBook> recipeBooks = recipeBookDAL.GetRecipeBooksForUser(user.UserId);
                        ViewData["recipeBooks"] = recipeBooks;
                    }
                    return View("Details", recipe);
                }
                else
                {
                    return new Utilities.NotFoundViewResult("NotFound");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return StatusCode(500, "Something went wrong. Please try again");
            }
        }

        /// <summary>
        /// Used for upserting a given user and recipe
        /// taste rating.
        /// </summary>
        /// <param name="id">The ID of the recipe being rated</param>
        /// <param name="rating">A rating of 1-5</param>
        /// <returns></returns>
        [Authorize]
        [HttpPost("Recipe/Rating/Taste")]
        public ActionResult TasteRating(
            int id,
            int rating)
        {
            try
            {
                int userID = userData.GetUser(User.FindFirst(ClaimTypes.Email).Value).UserId;
                if (recipeData.GetRecipe(id).UserId == userID)
                {
                    return Unauthorized("You cannot rate your own recipe");
                }

                recipeData.UpsertTasteRating(id, rating, userID);
                Recipe recipe = recipeData.GetRecipe(id);
                return View("Details", recipe);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return StatusCode(500, "Something went wrong. Please try again");
            }
        }

        /// <summary>
        /// Used for upserting a given user and recipe
        /// difficulty rating.
        /// </summary>
        /// <param name="id">The ID of the recipe being rated</param>
        /// <param name="rating">A rating of 1-5</param>
        /// <returns></returns>
        [Authorize]
        [HttpPost("Recipe/Rating/Difficulty")]
        public ActionResult DifficultyRating(
            int id,
            int rating)
        {
            try
            {
                int userID = userData.GetUser(User.FindFirst(ClaimTypes.Email).Value).UserId;
                if (recipeData.GetRecipe(id).UserId == userID)
                {
                    return Unauthorized("You cannot rate your own recipe");
                }

                recipeData.UpsertDifficultyRating(id, rating, userID);
                Recipe recipe = recipeData.GetRecipe(id);
                return View("Details", recipe);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return StatusCode(500, "Something went wrong. Please try again");
            }
        }

        /// <summary>
        /// Returns customer to new recipe page
        /// </summary>
        [HttpGet("Recipe/Create")]
        public ActionResult Create()
        {
            return View("Create");
        }

        /// <summary>
        /// Creates a new recipe
        /// </summary>
        /// <param name="recipe">Recipe model object to create</param>
        /// <param name="image">The new recipe image</param>
        [Authorize]
        [HttpPost("Recipe/Create")]
        public ActionResult Create(Recipe recipe, IFormFile image)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (image != null)
                    {
                        byte[] imageByte = Utilities.Images.ConvertUploadedImage(image);
                        recipe.Picture = imageByte;
                    }
                    var userEmail = User.FindFirst(ClaimTypes.Email).Value;
                    var user = userData.GetUser(userEmail);

                    var recipeID = this.recipeData.CreateRecipe(recipe, user.UserId, DateTime.Now);
                    return RedirectToAction("Details", new { id = recipeID });
                }
                else
                    return View("Create", recipe);
            }
            catch (MySqlException mySqlEx)
            {
                Console.WriteLine(mySqlEx);
                return StatusCode(500, "Something went wrong. Please try again");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return StatusCode(500, "Something went wrong. Please try again");
            }
        }

        /// <summary>
        /// Returns customer to edit recipe page
        /// </summary>
        [Authorize]
        [HttpGet("Recipe/Edit")]
        public IActionResult Edit(int recipeID)
        {
            Recipe recipe = recipeData.GetRecipe(recipeID);
            return View("Edit", recipe);
        }

        [Authorize]
        [HttpPost("Recipe/Edit")]
        public IActionResult Edit(Recipe newRecipe, IFormFile image, int recipeID)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Recipe oldRecipe = recipeData.GetRecipe(recipeID);
                    if (image != null)
                    {
                        byte[] imageByte = Utilities.Images.ConvertUploadedImage(image);
                        newRecipe.Picture = imageByte;
                    }
                    var success = this.recipeData.UpdateRecipe(oldRecipe, newRecipe);
                    return RedirectToAction("Details", new { id = recipeID });
                }
                else
                    return View("Edit", newRecipe);
            }
            catch (MySqlException mySqlEx)
            {
                Console.WriteLine(mySqlEx);
                return StatusCode(500, "Something went wrong. Please try again");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return StatusCode(500, "Something went wrong. Please try again");
            }
        }

        /// <summary>
        /// Provides real-time autocomplete functionality for ingredient searching on new recipe page
        /// </summary>
        [Produces("application/json")]
        [HttpGet("Recipe/IngredientSearch")]
        public IActionResult IngredientSearch(string searchTerm)
        {
            try
            {
                IngredientDAL ingredientDAL = new IngredientDAL();

                if (String.IsNullOrEmpty(searchTerm))
                {
                    searchTerm = HttpContext.Request.Query["term"].ToString();
                }

                List<Ingredient> ingredients = ingredientDAL.GetAllIngredients().Where(
                    i => i.Name.Contains(searchTerm, StringComparison.CurrentCultureIgnoreCase)).ToList();

                var matchedIngredients = ingredients.Select(i =>
                    new { label = i.Name, Value = i.Name }).ToList();

                return Json(matchedIngredients);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return StatusCode(500, "Something went wrong. Please try again");
            }
        }

        [Authorize]
        [HttpPost("Recipe/Delete")]
        public IActionResult DeleteRecipe(int id)
        {
            try
            {
                if(id <= 0)
                {
                    return StatusCode(500, "Invalid Recipe ID.");
                }

                this.recipeData.DeleteRecipe(id);
                return Ok();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return StatusCode(500, "Something went wrong. Please try again");
            }
        }
    }
}

TheKitchen/Views/Recipe/Create.cshtml
@model TheKitchen.Models.Recipe

@section Scripts {
    <script src="@Url.Content("~/js/CreateRecipe.js")" type="text/javascript"></script>
}

@section Styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/CreateRecipe.css" />
}

@{
    ViewData["Title"] = "Create Recipe";
}
<h3>Create a New Recipe</h3>
<br />
<form id="newRecipeForm" name="newRecipeForm" enctype="multipart/form-data" method="post" asp-controller="Recipe" asp-action="Create">
    <partial name="_RecipeForm" />
    <button type="submit" class="nav-link btn kitchen-btn" id="newRecipeButton">Create Recipe</button>
</form>
<br />

TheKitchen/Views/Recipe/Details.cshtml
@model TheKitchen.Models.Recipe
@using System.Security.Claims;

@section Scripts {
    <script src="@Url.Content("~/js/rateRecipe.js")" type="text/javascript"></script>
}

@{
    string ingredientString = Model.Title + "     ";
    for (var i = 0; i < Model.Ingredients.Count(); i++)
    {
        ingredientString += "   " + Model.Ingredients[i].Measurement + " " + Model.Ingredients[i].Ingredient + "     ";
    }
}

<div class="alert alert-success float-right center-block"
     role="alert" id="success-alert"
     style="display:none;">
    Successfully Added!
</div>

<button type="button"
        id="back-button"
        class="kitchen-recipe-details-back-btn">
    Back
</button>
<h3 id="model_title">@Model.Title</h3>
@if (User.Identity.IsAuthenticated)
{
    <a id="add-to-shopping-list-btn" id="delete-recipe"
       onclick="getModel('@ingredientString');">
       Add to Grocery List!
    </a>
}
<div class="d-flex">
    @if (Model.Picture == null)
    {
        <img class="kitchen-recipe-picture"
             src="~/images/recipe-image-placeholder.gif"
             alt="recipe image"
             id="recipe-picture">
    }
    else
    {
        <img class="kitchen-recipe-picture"
             src="data:image;base64,@System.Convert.ToBase64String(Model.Picture)"
             alt="recipe picture"
             id="recipe-picture">
    }
</div>
<br />
<h4>@Model.Description</h4>
<div class="d-flex justify-content-start">
    <div class="mr-3">
        <span class="kitchen-rating-label">Taste:</span>
        @for (int i = 0; i < 5; i++)
        {
            @if (i < Model.TasteRating)
            {
                <span class="fa fa-star kitchen-rating-starred"></span>
            }
            else
            {
                <span class="fa fa-star"></span>
            }
        }
    </div>
    <div class="mr-4">
        <span class="kitchen-rating-label">Difficulty:</span>
        @for (int i = 0; i < 5; i++)
        {
            @if (i < Model.DifficultyRating)
            {
                <span class="fa fa-star kitchen-rating-starred"></span>
            }
            else
            {
                <span class="fa fa-star"></span>
            }
        }
    </div>
    @if (User.Identity.IsAuthenticated
    && Model.UserId != TheKitchen.Utilities.User.GetUserIDFromEmail(User.FindFirst(ClaimTypes.Email).Value))
    {
        <div>
            <a id="kitchen-rate-recipe-anchor">
                Rate Recipe
            </a>
        </div>
        <div id="recipe-rating-form-div" class="d-none">
            <div id="recipe-taste-rating-div">

                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="kitchen-rating-label justify-content-end">Taste:</span>&nbsp;
                @for (int i = 1; i <= 5; i++)
                {
                    <button type="button"
                            class="fa fa-star kitchen-rating-button kichten-taste-rating-btn"
                            onclick="tasteRating(@Model.Id, @i);"></button>
                }
            </div>
            <div id="recipe-difficulty-rating-div">
                <span class="kitchen-rating-label">Difficulty:</span>&nbsp;
                @for (int i = 1; i <= 5; i++)
                {
                    <button type="submit"
                            class="fa fa-star kitchen-rating-button kichten-difficulty-rating-btn"
                            onclick="difficultyRating(@Model.Id, @i);"></button>
                }
            </div>
            <div id="rating-error"></div>
            <input type="hidden" id="recipeID" value="@Model.Id" />
        </div>
    }
</div>
<br />
<partial name="_AddRecipeToRecipeBook" model="@Model" view-data="ViewData" />
<br />
<br />
<h4 id="ingredient_header">Ingredients</h4>
<table class="table">
    <thead class="thead-light">
        <tr>
            <th scope="col">Measurement</th>
            <th scope="col">Ingredient</th>
        </tr>
    </thead>
    <tbody>
        @foreach (RecipeIngredient r in Model.Ingredients)
        {
            <tr>
                <td>@r.Measurement</td>
                <td>@r.Ingredient</td>
            </tr>
        }
    </tbody>
</table>
<h4>Directions</h4>
<table class="table">
    <thead class="thead-light">
        <tr>
            <th scope="col">Step</th>
            <th scope="col">Instruction</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Instruction i in Model.Directions)
        {
            <tr>
                <td>@i.Step.</td>
                <td>@i.InstructionText</td>
            </tr>
        }
    </tbody>
</table>
<br />

TheKitchen/Views/Recipe/Edit.cshtml
@model TheKitchen.Models.Recipe

@section Scripts {
    <script src="@Url.Content("~/js/CreateRecipe.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/js/deleteRecipe.js")" type="text/javascript"></script>
}

@section Styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/CreateRecipe.css" />
}

@{
    ViewData["Title"] = "Edit Recipe";
}
<button
        type="button"
        class="kitchen-delete-btn"
        data-toggle="modal"
        data-target="#confirm-delete-div">Delete Recipe</button>
<partial name="_ConfirmRecipeDelete" />
<div id="deletion-error"></div>
<h3>Edit a Recipe</h3>
<br />
<form id="newRecipeForm" name="newRecipeForm" enctype="multipart/form-data" method="post" asp-controller="Recipe" asp-action="Edit">
    <partial name="_RecipeForm" />
    <input hidden name="recipeID" id="recipeID" value="@Model.Id" />
    <button type="submit" class="nav-link btn kitchen-btn" id="newRecipeButton">Edit Recipe</button>
</form>
<br />

TheKitchen/Views/Recipe/Index.cshtml
@model IEnumerable<TheKitchen.Models.Recipe>
@{
    ViewData["Title"] = "Recipe Index";
}

<h3>Recipes</h3>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Description</th>
    </tr>
    @foreach (var recipe in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => recipe.Title)</td>
            <td>@Html.DisplayFor(modelItem => recipe.Description)</td>
        </tr>
    }
</table>

TheKitchen/Views/Recipe/_RecipeForm.cshtml
@model TheKitchen.Models.Recipe

<div class="form-group">
    <input type="text" class="form-control form-control-lg" id="recipeName" asp-for="Title" placeholder="Recipe Name" name="title" required>
    <span asp-validation-for="Title" class="text-danger"></span>
    <div id="confirm-small-title" class="kitchen-invalid-text d-none">
        The title must be at least 2 characters long.
    </div>
    <div id="confirm-long-title" class="kitchen-invalid-text d-none">
        The title cannot be longer than 45 characters.
    </div>
</div>
<div class="form-group">
    <textarea class="form-control form-control-lg" id="recipeDescription" asp-for="Description" rows="3" placeholder="Description" name="description" required></textarea>
    <span asp-validation-for="Description" class="text-danger"></span>
    <div id="confirm-small-description" class="kitchen-invalid-text d-none">
        The description must be at least 2 characters long.
    </div>
    <div id="confirm-long-description" class="kitchen-invalid-text d-none">
        The description cannot be longer than 500 characters.
    </div>
</div>
<div class="form-group addIngredients">
    <h4>Ingredients</h4>
    <div id="ingredientSearchbar">
        <input type="search" class="form-control form-control-lg" id="ingredientSearch" placeholder="Enter ingredient name here, then click Add.">
        <input type="button" class="nav-link btn kitchen-btn" id="addNewIngredient" value="Add" />
    </div>
    <br />
    <table class="table" id="ingredientTable" name="ingredientTable">
        <tbody>
            @if (Model != null && Model.Ingredients != null)
            {
                @for (int i = 0; i < Model.Ingredients.Count; i++)
                {
                    <tr>
                        <td>@Html.EditorFor(model => model.Ingredients[i].Measurement, new { htmlAttributes = new { @required = "required" } })</td>
                        <td>@Html.EditorFor(model => model.Ingredients[i].Ingredient, new { htmlAttributes = new { @class = "noTextborder", @readonly = "true" } })</td>
                        <td><input type="button" class="cancel" value="X"></td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <span asp-validation-for="Ingredients" class="text-danger"></span>
    <div id="confirm-duplicate-ingredient" class="kitchen-invalid-text d-none">
        That ingredient is already on the list.
    </div>
    <div id="confirm-empty-ingredient" class="kitchen-invalid-text d-none">
        You cannot add a blank ingredient.
    </div>
    <div id="confirm-no-ingredient" class="kitchen-invalid-text d-none">
        You must add at least one ingredient.
    </div>
</div>
<div class="form-group addInstructions">
    <h4>Instructions</h4>
    <div id="instructionTextBar">
        <input type="text" class="form-control form-control-lg" id="instructionText" placeholder="Enter instruction step here, then click Add.">
        <input type="button" class="nav-link btn kitchen-btn" id="addNewInstruction" value="Add" />
    </div>
    <br />
    <table class="table" id="instructionTable" name="instructionTable">
        <tbody>
            @if (Model != null && Model.Directions != null)
            {
                @for (int i = 0; i < Model.Directions.Count; i++)
                {
                    <tr>
                        <td><i class="fa fa-bars"></i></td>
                        <td>@Html.EditorFor(model => model.Directions[i].Step, new { htmlAttributes = new { @class = "noTextborder index", @readonly = "true" } })</td>
                        <td>@Html.TextAreaFor(model => model.Directions[i].InstructionText, 2, 50, new { @class = "noTextborder", @readonly = "true" })</td>
                        <td><input type="button" class="cancel" value="X"></td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <span asp-validation-for="Directions" class="text-danger"></span>
    <div id="confirm-short-instruction" class="kitchen-invalid-text d-none">
        Instruction must be at least 2 characters long.
    </div>
    <div id="confirm-no-instruction" class="kitchen-invalid-text d-none">
        You must add at least one instruction.
    </div>
</div>
<div class="custom-file">
    <input type="file" class="custom-file-input form-control-lg" accept=".jpg,.png" name="image" id="recipeFileUpload">
    <label class="custom-file-label" id="recipeFileUploadLabel" for="recipeFileUpload">
        Choose a Recipe Image
    </label>
</div>